# application variables
HOST_WITH_PORT: http://localhost:3000
YEAR: 2013

# meta information
SITE_NAME: Dummy Name
SITE_DESCRIPTION: Dummy Description
TITLE: Dummy Title

# When set to false the sdk is not included. 
# When chaning the id value remove the tmp folder
FACEBOOK_APP_ID: 345095095547911
FACEBOOK_NAME: Dummy Name
FACEBOOK_CAPTION: Help us spread the word
FACEBOOK_DESCRIPTION: About stuff and more

# Seems like twitter onlye share links that start with http://www
TWITTER_TEXT: Dummy Text

# mixpanel variables
MIXPANEL_SIGNUP_EVENT: signup
MIXPANEL_TOKEN: mixpanel

# email configuration
EMAIL_ADDRESS: smtp.mandrillapp.com
EMAIL_DOMAIN: yourdomain.com
EMAIL_PORT: 587
MANDRILL_USERNAME: username
MANDRILL_PASSWORD: password
